version: "3.9"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
        - "DJANGO_SECRET_KEY=django-insecure-xjulidsfhp_8w)42hi638s4p2=_kn_pcsh250qu88mv^gfi-_q"
        - "DJANGO_DEBUG=True"
        - "DJANGO_SECURE_SSL_REDIRECT=False"
        - "DJANGO_SECURE_HSTS_SECONDS=0"
        - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
        - "DJANGO_SECURE_HSTS_PRELOAD=False"
        - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
